### PR TITLE
fix: block permissions console errors

### LINKED ISSUE #183: Block Permissions - Browser Console Errors
Image

### PR DESCRIPTION
**Pull request by ThemeGravity**
Fixes #183 

The fix converts class components to modern functional components and removes not needed `withState` as a higher-order component wrapper. 

I also fixed checkbox functionality with proper immutable array handling and margin/size deprecation warnings.

### CODE REVIEW

**Review by cartpauj — APPROVED** [review]

File: addons/members-block-permissions/resources/js/editor/controls/cap-text-input.js [hunk 1]
```diff
@@ -8,39 +8,26 @@
...
-					} );
-				} }
-			/>
-		);
-	}
+function CapTextInput( props ) {
+	let { blockPermissionsCap } = props.attributes;
+
+	return (
+		<TextControl
```
Comment (allycspf) [inline addons/members-block-permissions/resources/js/editor/controls/cap-text-input.js:18]: @ThemeGravity There are a couple of deprecated warnings when "Condition: Show block to selected" and "Type: Capability" are selected:

```
deprecated.min.js?ver=e1f84915c5e8ae38964c:2 36px default size for wp.components.TextControl is deprecated since version 6.8 and will be removed in version 7.1. Note: Set the `__next40pxDefaultSize` prop to true to start opting into the new default size, which will become the default in a future version.

deprecated.min.js?ver=e1f84915c5e8ae38964c:2 Bottom margin styles for wp.components.TextControl is deprecated since version 6.7 and will be removed in version 7.0. Note: Set the `__nextHasNoMarginBottom` prop to true to start opting into the new styles, which will become the default in a future version.
```

**Review by allycspf — CHANGES_REQUESTED** [review]

**Review by allycspf — APPROVED** [review]
