### PR TITLE
Fix/login error redirection

### LINKED ISSUE #89: Behavior when entering incorrect data in the login shortcode
I use login shortcode but when user fill-in incorrect login/pass and press login it redirects to wp-login.php page and show error messages. Is it possible stay at the same page and see error messages below fields? I don't want the user to see the default WP login page.

### PR DESCRIPTION
**Pull request by ThemeGravity**
Resolves #89

### CODE REVIEW

File: inc/functions-shortcodes.php [hunk 1]
```diff
@@ -215,3 +218,51 @@ function members_login_form_shortcode() {
...
+    // If there's a valid referrer, and it's not the default log-in screen
+    if (
+        isset( $_SERVER['HTTP_REFERER'] ) &&
+        ! empty( $_SERVER['HTTP_REFERER'] ) &&
+        ( strstr( $_SERVER['HTTP_REFERER'],'wp-login' ) ||
+        strstr( $_SERVER['HTTP_REFERER'],'wp-admin' ) )
+    ) {
+        return $redirect_to;
+    } elseif ( empty( $user ) || is_wp_error( $user ) ) {
+        wp_redirect( str_replace('?login=failed', '', $_SERVER['HTTP_REFERER']) . '?login=failed' );
```
Comment (cartpauj) [inline inc/functions-shortcodes.php:243]: @ThemeGravity if I try to visit https://site.com/wp-login.php or https://site.com/wp-admin/ when not logged in. It creates an infinite redirect loop.

I think a better approach here would be to create a hidden input in the members login form and then check if that hidden field exists here before redirecting.

**Review by cartpauj — CHANGES_REQUESTED** [review]

**Comment by ThemeGravity** [comment]
@cartpauj My bad. Can you review it again?

File: inc/functions-shortcodes.php [hunk 2]
```diff
@@ -215,3 +218,50 @@ function members_login_form_shortcode() {
...
+ * @return string The HTML to output below the login form.
+ */
+function members_login_form_bottom() {
+    if (
+        isset( $_SERVER['HTTP_REFERER'] ) &&
+        ! empty( $_SERVER['HTTP_REFERER'] ) &&
+        ! strstr( $_SERVER['HTTP_REFERER'],'wp-login' ) &&
+        ! strstr( $_SERVER['HTTP_REFERER'],'wp-admin' )
+    ) {
+        $output = '<input type="hidden" name="members_redirect_to" value="' . esc_attr( $_SERVER['HTTP_REFERER'] ) . '" />';
```
Comment (cartpauj) [inline inc/functions-shortcodes.php:259]: @ThemeGravity I would just hard code this value to "1" or "true" or "yes". Rather than setting it to the referrer which may not always be available.

File: inc/functions-shortcodes.php [hunk 3]
```diff
@@ -215,3 +218,50 @@ function members_login_form_shortcode() {
...
+/**
+ * Filters the login form bottom output to add an error message if the login has failed.
+ *
+ * @since 3.2.18
+ *
+ * @return string The HTML to output below the login form.
+ */
+function members_login_form_bottom() {
+    if (
+        isset( $_SERVER['HTTP_REFERER'] ) &&
```
Comment (cartpauj) [inline inc/functions-shortcodes.php:254]: @ThemeGravity is any of this referrer checks necessary here? Can't we just always append these to the form?

**Review by cartpauj — CHANGES_REQUESTED** [review]

File: inc/functions-shortcodes.php (hunk 2 above)
Comment (ThemeGravity) [reply inc/functions-shortcodes.php]: @cartpauj I changed the value to 1

File: inc/functions-shortcodes.php (hunk 3 above)
Comment (ThemeGravity) [reply inc/functions-shortcodes.php]: @cartpauj We use `login_form_bottom` filter hook from `wp_login_form` function to display hidden input so you are right that referrer checks are not needed. I removed them in the last commit.

File: inc/functions-shortcodes.php [hunk 4]
```diff
@@ -215,3 +218,43 @@ function members_login_form_shortcode() {
...
+ * @param string $redirect_to    The redirect destination URL.
+ * @param string $request        The request URL.
+ * @param object $user           The user object.
+ * @return string                The redirect URL.
+ */
+function members_login_redirect( $redirect_to, $request, $user ) {
+    // If there's a valid referrer, and it's not the default log-in screen
+    if ( ! isset( $_POST['members_redirect_to'] ) ) {
+        return $redirect_to;
+    } elseif ( empty( $user ) || is_wp_error( $user ) ) {
```
Comment (cartpauj) [inline inc/functions-shortcodes.php:237]: @ThemeGravity as an extra sanity check, add `isset($user->ID) && $user->ID > 0` to be certain we have a valid User record here.

**Review by cartpauj — CHANGES_REQUESTED** [review]

File: inc/functions-shortcodes.php (hunk 4 above)
Comment (ThemeGravity) [reply inc/functions-shortcodes.php:236]: @cartpauj  I removed comment that is no longer valid after previous changes.

I don't quite understand what you mean.

The first check returns default `$redirect_to` if it's not members login form. 

The next condition:

```php
<?php
} elseif ( empty( $user ) || is_wp_error( $user ) ) {
```
checks if login fails (error or no user) so there's no `$user->ID`.

The last check keeps successfully logged in user on the same page.

Comment (cartpauj) [reply inc/functions-shortcodes.php:236]: Oh, you're right. Sorry. Ignore this.
